info:
  name: Edit Task
  type: http
  seq: 3

http:
  method: PATCH
  url: "{{base_url}}/tasks/1"
  body:
    type: json
    data: |-
      {
          "title": "Firsttt Visit Follow-up",
          "description": "Call the principal to confirm the presentation date."
      }
  auth:
    type: bearer
    token: 21|n9uzS9YgCVdkR0W0hH1ZsSqTwmfczM8sFYL8LvjRfe4e660a

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
