info:
  name: Get Tasks
  type: http
  seq: 1

http:
  method: GET
  url: "{{base_url}}/tasks"
  auth:
    type: bearer
    token: 20|BrNO1ysAbd0NZ7ZbVu2eQngfIKCNGmZwy4a5EwLUe2f341e5

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
